### ISSUE TITLE
dose not work when uploading non local file through cloud api

### ISSUE THREAD

**Issue by nanderer** [Pato05/uploadgram-app#10]
hi,

thanks a lot, app is working grate when uploading local files, but it fails without any message at all when you try to send a file accessed through the api with Android Samba Client (Dateizugriff auf SAMBA-Freigaben) - https://f-droid.org/packages/com.google.android.sambadocumentsprovider

others will probably use google or whatever cloud connecters but i prefere lokal storage i can trust, so please make it possible to upload non local files or at least show an error message (but implementing a temp download, upload and delete routine would be no problem i guess if you are unable to stream the file through the api)

thanks and keep up the good work

ps: is there a command line version i can use from debian?

**Comment by Pato05** [comment]
Hello. The app in the current beta version here on Github (and F-Droid) won't try downloading the file, but will only succeed if the file is directly from the local storage. Though if you join our telegram group you can find some other alpha builds which support such functionality.

Also available at:
- https://dl.uploadgram.me/61d832a9b53b7h (arm64)
- https://dl.uploadgram.me/61d832b07ac11h (arm32)

Regarding the CLI tool, currently there are no official ones currently.

Feel free to reopen this issue!
