### ISSUE TITLE
What is the privacy of files uploaded?

### ISSUE THREAD

**Issue by soupslurpr** [Pato05/uploadgram-app#13]
Hi i just wanted to know how does this upload files to telegram without a telegram account and what is the privacy of files i upload here?

**Comment by ShiSHcat** [comment]
The service works through Uploadgram's middle proxy backend (currently closed source) which does all the interactions with Telegram's MTProto API, holding all the users files in service telegram accounts, and exposing a simple HTTP(s) API to upload and download files from those service accounts.

You can find the service privacy policy [here](https://uploadgram.me/terms.html). Note that your files aren't encrypted and Uploadgram team can see your files. Also, your files are automatically scanned for malware.

**Comment by soupslurpr** [comment]
Ok thanks
