### ISSUE TITLE
Bigger files

### ISSUE THREAD

**Issue by dobrosketchkun** [Pato05/uploadgram-app#5]
Hello! 
As mentioned in #4 the size limit of a uploaded file is 2GB. Is it possible to cut a bigger file into pieces this size but make all the parts appear to the user as one? And if the user want to download it, the client just glues all the parts together.

**Comment by Pato05** [comment]
Hello. That is not possible and won't be because within Uploadgram, the Telegram limitations are respected. Please reopen if you have any other inherent question.
