### ISSUE TITLE
[BUG] Database does not support IPv6 addresses

### ISSUE THREAD

**Issue by r33int** [Pato05/uploadgram-app#6]
**Describe the bug**
When using the public instance (uploadgram.me), the following error happens when uploading a file from an IPv6 address:

![image](https://user-images.githubusercontent.com/22567851/115992624-e5ab8000-a5ce-11eb-954b-6d805a91c0aa.png)

It does not happen, however, when uploading from an IPv4 address. I believe this is due to the database structure not being adapted to the longer IPv6 addresses.

**To Reproduce**

- Access the web version from an IPv6 address
- Upload a file

**Expected behavior**
File should upload and the IPv6 address should be recorded into the database.

**Are you running the app from Android or from the Web?**
Browser, tested with Chrome and Firefox

**Comment by Pato05** [comment]
Hi! The issue should have been fixed, may you please try again?

**Comment by r33int** [comment]
Hello, I can confirm this is fixed, thanks a lot!

**Comment by Pato05** [comment]
Good to hear!
